
#hippunfold_training_data is extracted from zenodo zipfiles
hippunfold_lbl: /localScratch/akhan488/hcp_hippunfold_training/training_data/lbl/{subject}_hemi-{hemi}_lbl.nii.gz
hippunfold_img: /localScratch/akhan488/hcp_hippunfold_training/training_data/T1w/{subject}_hemi-{hemi}_T1w.nii.gz

dataset_json:
  name: HippT1w
  description: Zenodo HCP dataset for training hippunfold
  reference: Western University
  license: CC-BY-SA 4.0
  release: 0.1
  tensorImageSize: 3D
  modality:
    '0': T1
  labels:
   "0": "background"
   "1": "GM"
   "2": "SRLM"
   "3": "MTLC"
   "4": "Pial"
   "5": "HATA"
   "6": "IndGris"
   "7": "Cyst"
   "8": "DG"
  numTraining: 0
  numTest: 0
  training: []
  test: []
  


out_resolution: '128x256x128'
task: Task301_hcp_T1w
trainer: nnUNetTrainerV2
plans: nnUNetPlansv2.1
architecture: 3d_fullres
checkpoint: checkpoint_best #or checkpoint_final

nnunet_env:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: 'preprocessed'
  RESULTS_FOLDER: 'trained_models'
  nnUNet_n_proc_DA: 16

nnunet_env_tmp:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: '$TMPDIR/preprocessed'
  RESULTS_FOLDER: 'trained_models'

